In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

titre d'emploi : Le rôle ou le poste occupé (par exemple, analyste de données, ingénieur en IA)

années d'expérience : Nombre d'années d'expérience professionnelle

niveau d'éducation : Niveau d'études le plus élevé atteint

nombre de compétences: Nombre de compétences techniques ou professionnelles

industrie : Secteur d'activité auquel appartient l'emploi

taille de l'entreprise : Taille de l'entreprise (petite, moyenne, grande)

certifications  ::	Nombre de certifications professionnelles

salaire	Salaire annuel de l'employé

In [2]:
df = pd.read_csv("job_salary_prediction.csv")
df.head(10)

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069
5,AI Engineer,0,High School,4,Education,Enterprise,USA,No,2,180351
6,Backend Developer,6,High School,16,Manufacturing,Enterprise,Canada,No,3,165375
7,Machine Learning Engineer,4,Bachelor,18,Healthcare,Enterprise,Canada,Hybrid,5,202463
8,AI Engineer,5,Diploma,14,Telecom,Enterprise,Singapore,Yes,0,171834
9,Frontend Developer,18,PhD,2,Retail,Enterprise,India,Hybrid,5,128377

In [3]:
variable = [
    'job_title', 'education_level'
]

for i in variable:
    print(df[i].value_counts().to_frame())

                           count
job_title
Backend Developer          21125
Cybersecurity Analyst      20959
Product Manager            20950
AI Engineer                20945
Data Scientist             20890
DevOps Engineer            20889
Software Engineer          20876
Data Analyst               20722
Cloud Engineer             20686
Machine Learning Engineer  20677
Business Analyst           20648
Frontend Developer         20633
                 count
education_level
Master           50352
High School      50065
Bachelor         49950
PhD              49857
Diploma          49776

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  str
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  str
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  str
 5   company_size      250000 non-null  str
 6   location          250000 non-null  str
 7   remote_work       250000 non-null  str
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), str(6)
memory usage: 19.1 MB

In [5]:
df.isna().sum()

job_title           0
experience_years    0
education_level     0
skills_count        0
industry            0
company_size        0
location            0
remote_work         0
certifications      0
salary              0
dtype: int64

In [6]:
df.describe()

       experience_years   skills_count  certifications         salary
count     250000.000000  250000.000000   250000.000000  250000.000000
mean          10.005408       9.997812        2.491928  145718.080524
std            6.060602       5.479288        1.706475   37407.952729
min            0.000000       1.000000        0.000000   31867.000000
25%            5.000000       5.000000        1.000000  119358.000000
50%           10.000000      10.000000        2.000000  143453.000000
75%           15.000000      15.000000        4.000000  169492.000000
max           20.000000      19.000000        5.000000  333046.000000

In [7]:
df.duplicated().sum()

np.int64(0)